package com.bjpowernode.pojo;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private String aName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_pass
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private String aPass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_name
     *
     * @return the value of admin.a_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_name
     *
     * @param aName the value for admin.a_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_pass
     *
     * @return the value of admin.a_pass
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public String getaPass() {
        return aPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_pass
     *
     * @param aPass the value for admin.a_pass
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setaPass(String aPass) {
        this.aPass = aPass == null ? null : aPass.trim();
    }
}