package com.bjpowernode.pojo;

import java.util.Date;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_content
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private String pContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_price
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Integer pPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_image
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private String pImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_number
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Integer pNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.type_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.p_date
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    private Date pDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_id
     *
     * @return the value of product_info.p_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_id
     *
     * @param pId the value for product_info.p_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_name
     *
     * @return the value of product_info.p_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_name
     *
     * @param pName the value for product_info.p_name
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_content
     *
     * @return the value of product_info.p_content
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public String getpContent() {
        return pContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_content
     *
     * @param pContent the value for product_info.p_content
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpContent(String pContent) {
        this.pContent = pContent == null ? null : pContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_price
     *
     * @return the value of product_info.p_price
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Integer getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_price
     *
     * @param pPrice the value for product_info.p_price
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpPrice(Integer pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_image
     *
     * @return the value of product_info.p_image
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public String getpImage() {
        return pImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_image
     *
     * @param pImage the value for product_info.p_image
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpImage(String pImage) {
        this.pImage = pImage == null ? null : pImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_number
     *
     * @return the value of product_info.p_number
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Integer getpNumber() {
        return pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_number
     *
     * @param pNumber the value for product_info.p_number
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpNumber(Integer pNumber) {
        this.pNumber = pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.type_id
     *
     * @return the value of product_info.type_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.type_id
     *
     * @param typeId the value for product_info.type_id
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.p_date
     *
     * @return the value of product_info.p_date
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public Date getpDate() {
        return pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.p_date
     *
     * @param pDate the value for product_info.p_date
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }
}