package com.bjpowernode.mapper;

import com.bjpowernode.pojo.ProductType;
import com.bjpowernode.pojo.ProductTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int countByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int deleteByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    List<ProductType> selectByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    ProductType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Tue Aug 08 17:07:14 CST 2023
     */
    int updateByPrimaryKey(ProductType record);
}