sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hfq123456
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tJVAwzqLSVrKxjyz3oE
      access-key-secret: gaVmHRp0595uzEbHNiiSwwHOEkbiVY
      bucket-name: web-tliasqw
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
